language: node_js

sudo: required

node_js:
  - "10.15.3"

install:
  - npm install

jobs:
  include:
    - stage: tests
      name: "lint"
      script: npm run lint

    - stage: tests
      name: "test"
      script: npm run test
